name: Build Vue
on:
  push:
    branches:
      -main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: SerhiiKa/VuePagesAction@1.0.2
      with:
        username: 'SerhiiKa'
        reponame: 'helpy-sheets'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
